template_path: genie.yaml
stack_name: genie
parameters:
  # AWS batch requires the instance to have pre-installed packages.
  # VEP installation
  # Distibution: Amazon Linux.
  ComputeImageId: ami-033b8c0b4b16a03cd
  # 95VEP: ami-0a0966a44218e21ab
  DevComputeImageId: ami-0a0966a44218e21ab

  MainImage: sagebionetworks/genie:latest
  MutationImage: sagebionetworks/genie:vcf2maf
  # AWS user ARN
  SubmitterArn: arn:aws:iam::055273631518:user/thomas.yu@sagebase.org