template_path: genie.yaml
stack_name: geniestaging
parameters:
  # AWS batch requires the instance to have pre-installed packages.
  # Distibution: Amazon Linux.
  # 95VEP: ami-0a0966a44218e21ab
  ComputeImageId: ami-0a0966a44218e21ab
  MainImage: sagebionetworks/genie:develop
  MutationImage: sagebionetworks/genie:vcf2maf-develop

  Department: "CompOnc"
  Project: "genie"
  OwnerEmail: "thomas.yu@sagebase.org"